const {test}=require('node:test');
const assert=require('node:assert/strict');
const {MockStore}=require('../.angular/mock-tests/services/mock/mock-store');
const {MockModeration,moderation}=require('../.angular/mock-tests/services/mock/mock-moderation');
const {MockPlaylists}=require('../.angular/mock-tests/services/mock/mock-playlists');
const {createSeedState}=require('../.angular/mock-tests/data/seed-state');
test('private reports, administrator permissions, suspension, hiding and durable audit',async()=>{
 const s=createSeedState(), [a,b,c]=s.profiles, p=s.playlists[0];
 moderation(s).members.find(m=>m.user_id===a.id).role='admin';
 s.session={userId:b.id};
 const storage={value:JSON.stringify(s),getItem(){return this.value},setItem(k,v){this.value=v}};
 const store=new MockStore(storage); store.controls.latencyMs=0;
 const service=new MockModeration(store), playlists=new MockPlaylists(store);
 await service.report('playlist',p.id,'Please review');
 await assert.rejects(service.report('playlist',p.id,'duplicate'));
 await assert.rejects(service.members());
 await assert.rejects(service.act('grant_admin','member',b.id,'Escalate'));
 await store.write('test',s=>{s.session={userId:c.id}});
 assert.equal((await service.reports()).length,0);
 await store.write('test',s=>{s.session={userId:a.id}});
 const report=(await service.reports())[0];
 await service.act('hide','playlist',p.id,'Review confirmed');
 assert.equal((await service.reports()).find(r=>r.id===report.id).status,'resolved');
 assert.equal((await playlists.get(p.id)).hidden,true);
 await assert.rejects(service.act('suspend','member',a.id,'Self'));
 await service.act('suspend','member',b.id,'Repeated abuse');
 assert.equal((await service.audit()).length,3);
 await store.write('test',s=>{s.session={userId:b.id}});
 await assert.rejects(playlists.list());
 await assert.rejects(service.report('profile',c.id,'Report'));
 await store.write('test',s=>{s.session={userId:c.id}});
 assert.ok(!(await playlists.list()).some(x=>x.id===p.id));
 await assert.rejects(playlists.get(p.id));
 await store.write('test',s=>{s.session={userId:a.id}});
 await service.act('restore','playlist',p.id,'Appeal accepted');
 await service.act('unsuspend','member',b.id,'Appeal accepted');
 const reloaded=new MockStore(storage);reloaded.controls.latencyMs=0;
 assert.equal((await new MockModeration(reloaded).audit()).length,5);
});

test('admin and member reports resolve together and restoration stays closed',async()=>{
 const s=createSeedState(), [a,b]=s.profiles, p=s.playlists[0];
 moderation(s).members.find(m=>m.user_id===a.id).role='admin';
 s.session={userId:b.id};
 const storage={value:JSON.stringify(s),getItem(){return this.value},setItem(k,v){this.value=v}};
 const store=new MockStore(storage);store.controls.latencyMs=0;
 const service=new MockModeration(store), playlists=new MockPlaylists(store);
 await service.report('playlist',p.id,'Member report');
 await store.write('test',s=>{s.session={userId:a.id}});
 await service.report('playlist',p.id,'Admin report');
 await service.act('hide','playlist',p.id,'Confirmed');
 assert.deepEqual((await service.reports()).map(r=>r.status),['resolved','resolved']);
 assert.equal((await playlists.list()).find(x=>x.id===p.id).hidden,true);
 await service.act('restore','playlist',p.id,'Appeal');
 assert.equal((await playlists.get(p.id)).hidden,false);
 assert.ok((await service.reports()).every(r=>r.status==='resolved'));
 await store.write('test',s=>{s.session={userId:b.id}});
 assert.equal((await service.reports()).length,1);
 assert.equal((await playlists.get(p.id)).hidden,false);
});
