import { readFileSync, writeFileSync, unlinkSync, openSync, closeSync, existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { loadEnvFile } from 'node:process';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

process.chdir(fileURLToPath(new URL('..', import.meta.url)));
const [action, target, ...extra] = process.argv.slice(2);
if (!['build', 'deploy', 'preview'].includes(action) || !['staging', 'production'].includes(target) || extra.length) {
  console.error('Usage: node scripts/deploy.mjs <build|preview|deploy> <staging|production>');
  process.exit(1);
}

let locked = false;
const lock = `.deploy-${target}.lock`;
const generated = `src/environments/environment.${target}.generated.ts`;
try {
  const config = JSON.parse(readFileSync(`deploy/${target}.json`, 'utf8'));
  const { workerName, supabase, sentry } = config;
  const wrangler = JSON.parse(readFileSync('wrangler.jsonc', 'utf8'));
  if (wrangler.env?.[target]?.name !== workerName) throw new Error('Worker name must match wrangler.jsonc for this environment.');
  if (!/^[a-z0-9][a-z0-9-]*$/.test(workerName ?? '')) throw new Error('Set a valid workerName in deployment config.');
  if (!/^https:\/\/[a-z]{20}\.supabase\.co$/.test(supabase?.url ?? '')) throw new Error('Set the hosted Supabase URL in deployment config.');
  if (!/^sb_publishable_[A-Za-z0-9_-]+$/.test(supabase?.publishableKey ?? '')) throw new Error('Set a Supabase publishable key, never a secret or service-role key.');
  const other = JSON.parse(readFileSync(`deploy/${target === 'staging' ? 'production' : 'staging'}.json`, 'utf8'));
  if (workerName === other.workerName || supabase.url === other.supabase.url) throw new Error('Staging and production must use different Workers and Supabase projects.');
  if (existsSync(`.env.${target}`)) loadEnvFile(`.env.${target}`);
  const revision = spawnSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' });
  const release = process.env.SENTRY_RELEASE || revision.stdout?.trim();
  if (sentry?.dsn && !release) throw new Error('Set SENTRY_RELEASE when building outside a Git checkout.');
  if (sentry?.dsn && action === 'deploy' && !process.env.SENTRY_AUTH_TOKEN) throw new Error('Set SENTRY_AUTH_TOKEN before deploying so source maps can be uploaded.');
  closeSync(openSync(lock, 'wx'));
  locked = true;
  writeFileSync(generated, `// Generated by scripts/deploy.mjs; public browser configuration only.\nexport const environment = ${JSON.stringify({ supabase: { url: supabase.url, publishableKey: supabase.publishableKey }, sentry: { dsn: sentry?.dsn || '', environment: target, release: release || 'local' } }, null, 2)} as const;\n`);
  console.log(`${action}: ${target} → ${workerName} (${supabase.url})`);
  function run(args) {
    const result = spawnSync('pnpm', args, { stdio: 'inherit', env: process.env });
    if (result.error || result.status !== 0) throw new Error(`Command failed: pnpm ${args.slice(0, 3).join(' ')}`);
  }
  run(['typecheck']);
  run(['exec', 'ng', 'build', '--configuration', `production,release-${target}`, '--output-path', `dist/${target}`]);
  const output = `dist/${target}/browser`;
  if (sentry?.dsn) {
    process.env.SENTRY_ORG = sentry.org;
    process.env.SENTRY_PROJECT = sentry.project;
    run(['exec', 'sentry-cli', 'sourcemaps', 'inject', output]);
    if (process.env.SENTRY_AUTH_TOKEN) {
      run(['exec', 'sentry-cli', 'sourcemaps', 'upload', '--release', release, output]);
    } else {
      console.warn('Source-map upload skipped: SENTRY_AUTH_TOKEN is unset. Deployment will require it.');
    }
  }
  // Hidden maps must also be removed from the directory served by Cloudflare.
  function removeMaps(directory) {
    if (!existsSync(directory)) return;
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      const path = join(directory, entry.name);
      if (entry.isDirectory()) removeMaps(path);
      else if (entry.name.endsWith('.map')) unlinkSync(path);
    }
  }
  removeMaps(output);
  if (action !== 'build') {
    run(['dlx', 'wrangler@4', 'deploy', '--config', 'wrangler.jsonc', '--env', target, ...(action === 'preview' ? ['--dry-run'] : [])]);
  }
} catch (error) {
  console.error(error.code === 'EEXIST' ? `Another ${target} build is running. If it crashed, remove ${lock}.` : error.message);
  process.exitCode = 1;
} finally {
  if (locked) {
    if (existsSync(generated)) unlinkSync(generated);
    unlinkSync(lock);
  }
}
