import { readFileSync, writeFileSync, unlinkSync, openSync, closeSync, existsSync } from 'node:fs';
import { loadEnvFile } from 'node:process';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

process.chdir(fileURLToPath(new URL('..', import.meta.url)));
const [action, target, ...extra] = process.argv.slice(2);
if (!['build', 'deploy', 'preview'].includes(action) || !['staging', 'production'].includes(target) || extra.length) {
  console.error('Usage: node scripts/deploy.mjs <build|preview|deploy> <staging|production>');
  process.exit(1);
}

let locked = false;
const lock = `.deploy-${target}.lock`;
const generated = `src/environments/environment.${target}.generated.ts`;
try {
  const config = JSON.parse(readFileSync(`deploy/${target}.json`, 'utf8'));
  const { workerName, supabase } = config;
  const wrangler = JSON.parse(readFileSync('wrangler.jsonc', 'utf8'));
  if (wrangler.env?.[target]?.name !== workerName) throw new Error('Worker name must match wrangler.jsonc for this environment.');
  if (!/^[a-z0-9][a-z0-9-]*$/.test(workerName ?? '')) throw new Error('Set a valid workerName in deployment config.');
  if (!/^https:\/\/[a-z]{20}\.supabase\.co$/.test(supabase?.url ?? '')) throw new Error('Set the hosted Supabase URL in deployment config.');
  if (!/^sb_publishable_[A-Za-z0-9_-]+$/.test(supabase?.publishableKey ?? '')) throw new Error('Set a Supabase publishable key, never a secret or service-role key.');
  const other = JSON.parse(readFileSync(`deploy/${target === 'staging' ? 'production' : 'staging'}.json`, 'utf8'));
  if (workerName === other.workerName || supabase.url === other.supabase.url) throw new Error('Staging and production must use different Workers and Supabase projects.');
  if (existsSync(`.env.${target}`)) loadEnvFile(`.env.${target}`);
  closeSync(openSync(lock, 'wx'));
  locked = true;
  writeFileSync(generated, `// Generated by scripts/deploy.mjs; public browser configuration only.\nexport const environment = ${JSON.stringify({ supabase: { url: supabase.url, publishableKey: supabase.publishableKey } }, null, 2)} as const;\n`);
  console.log(`${action}: ${target} → ${workerName} (${supabase.url})`);
  function run(args) {
    const result = spawnSync('pnpm', args, { stdio: 'inherit', env: process.env });
    if (result.error || result.status !== 0) throw new Error(`Command failed: pnpm ${args.slice(0, 3).join(' ')}`);
  }
  run(['typecheck']);
  run(['exec', 'ng', 'build', '--configuration', `production,release-${target}`, '--output-path', `dist/${target}`]);
  if (action !== 'build') {
    run(['dlx', 'wrangler@4', 'deploy', '--config', 'wrangler.jsonc', '--env', target, ...(action === 'preview' ? ['--dry-run'] : [])]);
  }
} catch (error) {
  console.error(error.code === 'EEXIST' ? `Another ${target} build is running. If it crashed, remove ${lock}.` : error.message);
  process.exitCode = 1;
} finally {
  if (locked) {
    if (existsSync(generated)) unlinkSync(generated);
    unlinkSync(lock);
  }
}
